name: Python application

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'  
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'  

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest  # Simplified to run only on ubuntu-latest for Docker compatibility

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"  # Specifying one Python version for simplicity

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest requests
        pip install -r requirements.txt

    - name: Start Docker Container
      run: |
        docker-compose -f ./FreeAPI up --build --attach backend
        
    - name: Check Docker Container Logs
      run: docker-compose -f ./FreeAPI logs backend


    - name: Run Pytest
      run: |
        pytest tests/unit

    - name: Stop Docker Container
      if: always()  # Ensures this step runs even if previous steps fail
      run: |
        docker-compose -f ./FreeAPI/docker-compose.yml down

